### ISSUE TITLE
YourTTS_zeroshot_VC_demo.ipynb

### ISSUE THREAD

**Issue by stalevna** [Edresson/YourTTS#10]
Hi!
I am trying to run YourTTS_zeroshot_VC_demo.ipynb and there seems to be access changes to the file best_model.pth.tar
I am downloading it right now and I will manually upload it, so that I can run the notebook, but could you kindly fix the access rights so that others could easily run it like it was before. Thank you in advance!
![image](https://user-images.githubusercontent.com/53433879/158116180-9ed11223-df7d-430a-9dad-fa6638e82789.png)

**Comment by shagho** [comment]
@stalevna
Hello!
for solving this problem for last file downloading use this bash script.
`!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=FILEID' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=FILEID" -O FILENAME && rm -rf /tmp/cookies.txt`
in above script just replace FILEID with drive file id and FILENAME with output name you want to save.

**Comment by makerjackie** [comment]
when try exec [YourTTS-zeroshot-TTS Colab notebook](https://colab.research.google.com/drive/1ftI0x16iqKgiQFgTjTDgRpOM1wC1U-yS?usp=sharing)

I encounter a problem
> FileNotFoundError: [Errno 2] No such file or directory: 'best_model.pth.tar'

**Comment by shagho** [comment]
> when try exec [YourTTS-zeroshot-TTS Colab notebook](https://colab.research.google.com/drive/1ftI0x16iqKgiQFgTjTDgRpOM1wC1U-yS?usp=sharing)
> 
> I encounter a problem
> 
> > FileNotFoundError: [Errno 2] No such file or directory: 'best_model.pth.tar'

because the model didn't download and use this script to download the model
`wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=FILEID' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=FILEID" -O FILENAME && rm -rf /tmp/cookies.txt`

in above script just replace FILEID with drive file id and FILENAME with output name you want to save.

**Comment by makerjackie** [comment]
thx

**Comment by shagho** [comment]
you're welcome!
