### ISSUE TITLE
Inference based on YourTTS-zeroshot-VC-demo

### ISSUE THREAD

**Issue by stalevna** [Edresson/YourTTS#11]
Hi!
I tried to inference some audios using files that were generated by training vits model on ljspeech dataset.
![image](https://user-images.githubusercontent.com/53433879/158580729-a122a0e3-2c96-4314-aa18-7feedc68473d.png)
I substituted files in the YourTTS-zeroshot-VC-demo for my own
![image](https://user-images.githubusercontent.com/53433879/158581283-d0894370-d661-4e52-8e33-f4bddab79ca9.png)
However I noticed that your model checkpoint  'best_model.pth.tar' weighs 380 Mb, while my checkpoint_25.pth.tar weighs 1.1Gb, even with mixed_precision = true.

So I upload and prepare audio files and make target_emb, driving_emb and driving_spec, but when I try to convert the voice I get an error: 
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

![image](https://user-images.githubusercontent.com/53433879/158583037-6b881bca-caf8-4f3a-9b3a-b824733f4db9.png)

Did anyone else run into such problem? Please, help

**Comment by Edresson** [comment]
Hi, 
Looks like that use_d_vector is false. So it means that you are not using external speakers embeddings. The demo provided only works for external speaker embeddings training. You need to modify it, instead of providing speaker embeddings (that is a Float Tensor) you must provide a Long tensor with the target speaker id.
